"""
Cerberus Event Schemas - Standardized event formats for all components
"""
from datetime import datetime
from typing import Dict, List, Optional, Any, Literal
from pydantic import BaseModel, Field
from uuid import uuid4


class RequestData(BaseModel):
    """HTTP request data"""
    method: str
    url: str
    headers: Dict[str, str]
    body: str = ""
    query_params: Dict[str, str] = {}


class GeoIPData(BaseModel):
    """Geographic IP information"""
    country: str
    region: Optional[str] = None
    city: Optional[str] = None
    asn: Optional[str] = None
    is_tor: bool = False
    is_vpn: bool = False


class ScoreData(BaseModel):
    """Detection scores from various engines"""
    modsecurity: float = 0.0
    ml_anomaly: float = 0.0
    combined: float = 0.0


class BaseEvent(BaseModel):
    """Base event with common fields"""
    event_id: str = Field(default_factory=lambda: f"evt_{uuid4().hex[:8]}")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    source: Literal["gatekeeper", "switch", "labyrinth", "sentinel"]
    event_type: str
    session_id: str
    client_ip: str
    meta: Dict[str, Any] = {}


class POITaggedEvent(BaseEvent):
    """Event: Request tagged as Person of Interest"""
    event_type: Literal["poi_tagged"] = "poi_tagged"
    request: RequestData
    tags: List[str] = []
    scores: ScoreData
    action: Literal["tagged"] = "tagged"
    geoip: Optional[GeoIPData] = None


class SessionPinnedEvent(BaseEvent):
    """Event: Session pinned to Labyrinth"""
    event_type: Literal["session_pinned"] = "session_pinned"
    fingerprint: str
    action: Literal["redirected"] = "redirected"
    target: Literal["labyrinth", "production"] = "labyrinth"
    pin_duration_hours: int = 24
    reason: str


class PayloadData(BaseModel):
    """Extracted attack payload"""
    type: str  # sql_injection, xss, command_injection, etc.
    value: str
    location: str  # e.g., "body.username", "query.id"
    confidence: float


class PayloadCapturedEvent(BaseEvent):
    """Event: Payload captured in Labyrinth"""
    event_type: Literal["payload_captured"] = "payload_captured"
    capture_id: str = Field(default_factory=lambda: f"cap_{uuid4().hex[:8]}")
    request: RequestData
    extracted_payloads: List[PayloadData] = []
    evidence_url: str


class SimulationResult(BaseModel):
    """Result of payload simulation"""
    verdict: Literal["exploit_possible", "exploit_improbable"]
    severity: float  # 0-10 scale
    attack_type: str
    exploitation_evidence: str
    affected_resources: List[str] = []
    reproduction_steps: List[str] = []


class SimulationCompleteEvent(BaseEvent):
    """Event: Simulation completed"""
    event_type: Literal["simulation_complete"] = "simulation_complete"
    simulation_id: str = Field(default_factory=lambda: f"sim_{uuid4().hex[:8]}")
    payload_id: str
    result: SimulationResult
    execution_time_ms: int


class RuleMatch(BaseModel):
    """WAF rule match specification"""
    type: Literal["string", "regex", "header_combo"]
    pattern: str
    location: List[str] = ["args", "body"]  # Where to search
    flags: Dict[str, Any] = {}


class RuleEvidence(BaseModel):
    """Evidence supporting a rule"""
    simulation_id: str
    sample_payloads: List[str]
    severity: float
    attack_type: str


class WAFRule(BaseModel):
    """WAF rule definition"""
    rule_id: str = Field(default_factory=lambda: f"rule_{uuid4().hex[:8]}")
    created_by: str = "sentinel"
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    priority: int = 100  # Higher = evaluated first
    match: RuleMatch
    action: Literal["block", "challenge", "tag", "log"]
    confidence: float
    evidence: RuleEvidence
    valid_from: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    expires_at: Optional[str] = None
    audit: Dict[str, Any] = {}
    enabled: bool = True


class RuleGeneratedEvent(BaseEvent):
    """Event: Rule generated by Sentinel"""
    event_type: Literal["rule_generated"] = "rule_generated"
    rule: WAFRule
    action: Literal["auto_applied", "pending_review", "logged_only"]
    reason: str


class AttackerProfile(BaseModel):
    """Behavioral profile of an attacker"""
    session_id: str
    action_sequence: List[str]
    ttps: List[str]  # MITRE ATT&CK technique IDs
    intent: str  # reconnaissance, exploitation, data_exfiltration, etc.
    sophistication_score: float  # 0-10
    cluster_id: int


# Sample event instances for testing

SAMPLE_POI_EVENT = POITaggedEvent(
    source="gatekeeper",
    session_id="sess_demo_001",
    client_ip="203.0.113.42",
    request=RequestData(
        method="GET",
        url="/admin/users?id=1' OR '1'='1",
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
            "Host": "example.com",
            "Accept": "*/*"
        },
        body="",
        query_params={"id": "1' OR '1'='1"}
    ),
    tags=["poi", "sql_injection_suspected", "ml_high_score"],
    scores=ScoreData(
        modsecurity=85.0,
        ml_anomaly=0.92,
        combined=0.94
    ),
    geoip=GeoIPData(
        country="CN",
        asn="AS4134",
        is_tor=False,
        is_vpn=False
    )
)

SAMPLE_PAYLOAD_EVENT = PayloadCapturedEvent(
    source="labyrinth",
    session_id="sess_demo_001",
    client_ip="203.0.113.42",
    capture_id="cap_demo_001",
    request=RequestData(
        method="POST",
        url="/api/v1/users",
        headers={
            "Content-Type": "application/json",
            "Authorization": "Bearer fake_token_12345"
        },
        body='{"name":"admin\' OR \'1\'=\'1--","email":"attacker@evil.com"}',
        query_params={}
    ),
    extracted_payloads=[
        PayloadData(
            type="sql_injection",
            value="admin' OR '1'='1--",
            location="json_body.name",
            confidence=0.95
        )
    ],
    evidence_url="s3://cerberus-evidence/cap_demo_001.json"
)

SAMPLE_RULE = WAFRule(
    rule_id="rule_demo_001",
    priority=100,
    match=RuleMatch(
        type="regex",
        pattern=r"'\\s*(OR|AND)\\s*'[^']*'\\s*=\\s*'[^']*",
        location=["args", "body", "json_values"],
        flags={"caseless": True}
    ),
    action="block",
    confidence=0.95,
    evidence=RuleEvidence(
        simulation_id="sim_demo_001",
        sample_payloads=["admin' OR '1'='1--", "' OR 1=1--"],
        severity=9.2,
        attack_type="sql_injection"
    ),
    audit={
        "sim_verdict": "exploit_possible",
        "attacker_ttp": ["T1190"]
    }
)


def event_to_json(event: BaseEvent) -> str:
    """Serialize event to JSON string"""
    return event.model_dump_json(indent=2)


def event_from_json(json_str: str, event_class: type) -> BaseEvent:
    """Deserialize event from JSON string"""
    return event_class.model_validate_json(json_str)
